#!/bin/bash
#If you wish to replace our default value for apc memory in /etc/php5/conf.d/apc.ini,
#edit the APC_MEMORY variable in /etc/mercury/tuneable_configs

if [[ -a /etc/mercury/tuneable_configs ]]; then
. /etc/mercury/tuneable_configs
fi

RAM=`grep MemTotal /proc/meminfo | sed 's/[^0-9]*//g'`

if [[ -n "$APC_MEMORY" ]]; then
   echo "$APC_MEMORY"
elif (($RAM>=2000000)); then
    echo "128"
elif (($RAM>=1000000)); then
    echo "96"
else
    echo "64"
fi

