#!/bin/bash
#set apc memory usage

RAM=`grep MemTotal /proc/meminfo | sed 's/[^0-9]*//g'`

if [[ -a /etc/php5/conf.d/memory.sh ]]; then
   /etc/php5/conf.d/memory.sh
elif (($RAM>=50000000)); then
    echo "128"
elif (($RAM>=25000000)); then
    echo "128"
elif (($RAM>=15000000)); then
    echo "128"
elif (($RAM>=8000000)); then
    echo "128"
elif (($RAM>=4000000)); then
    echo "128"
elif (($RAM>=2000000)); then
    echo "128"
elif (($RAM>=1000000)); then
    echo "96"
else
    echo "64"
fi

