#!/bin/bash
#apparmor mysql config

if [[ -a /etc/apparmor.d/mysql ]]; then
    /etc/apparmor.d/mysql
else
    echo "/mnt/mysql/lib/ r,"
    echo "/mnt/mysql/lib/** rwk,"
    echo "/mnt/mysql/log/ r,"
    echo "/mnt/mysql/log/* rw,"
    echo "/mnt/mysql/tmp/ rw,"
    echo "/mnt/mysql/tmp/** rwkl,"
fi


