#!/bin/sh

OUTPUT=""

if [ -e /etc/debian_version ]; then
    # debian based
    OUTPUT=$OUTPUT'\n'`echo group:deb`
    if [ -e /etc/lsb-release ]; then
        # variant
        . /etc/lsb-release
        OUTPUT=$OUTPUT'\n'`echo group:$DISTRIB_CODENAME`
        DEBIAN_VERSION=$(echo "$DISTRIB_ID" | tr '[A-Z' '[a-z]')
        OUTPUT=$OUTPUT'\n'`echo group:$DEBIAN_VERSION`
    fi
fi

# get the proper architecture
ARCH=`uname -m`
case "$ARCH" in
    "x86_64")
        OUTPUT=$OUTPUT'\n'`echo group:amd64`
	;;
    "i686")
        OUTPUT=$OUTPUT'\n'`echo group:i386`
	;;
esac


# output the result of all the group probing
# (interpreting the backslashed newlines)
echo -e $OUTPUT
