#!/bin/bash
#If you wish to replace our default value for innodb log file size in /etc/mysql/my.cnf,
#edit the INNODB_LOG_FILE_SIZE variable in /etc/mercury/server_tuneables

if [[ -a /etc/mercury/server_tuneables ]]; then
. /etc/mercury/server_tuneables
fi

if [[ -z "$INNODB_LOG_FILE_SIZE" ]]; then
    #1073741824 is 1 GB in bytes
    INNODB_LOG_FILE_SIZE="1073741824"
fi

if [[ -a /var/lib/mysql/ib_logfile0 && ( `stat -c '%s' /var/lib/mysql/ib_logfile0` -ne "$INNODB_LOG_FILE_SIZE" ) ]]; then
    service mysql stop >/dev/null
    rm /var/lib/mysql/ib_logfile* >/dev/null
    service mysql start >/dev/null
fi

echo "$INNODB_LOG_FILE_SIZE"
