#!/bin/bash
#If you wish to replace our default value for innode buffer pool size in /etc/mysql/my.cnf,
#edit the INNODB_BUFFER_POOL_SIZE variable in /etc/mercury/server_tuneables

if [[ -a /etc/mercury/server_tuneables ]]; then
. /etc/mercury/server_tuneables
fi

RAM=`grep MemTotal /proc/meminfo | sed 's/[^0-9]*//g'`

if [[ -n "$INNODB_BUFFER_POOL_SIZE" ]]; then
   echo "$INNODB_BUFFER_POOL_SIZE"
elif (($RAM>=8000000)); then
    echo "2048"
elif (($RAM>=4000000)); then
    echo "1024"
elif (($RAM>=2000000)); then
    echo "512"
elif (($RAM>=1000000)); then
    echo "256"
else
    echo "128"
fi


