#!/bin/sh
#set apc memory usage

MEM=`/var/lib/bcfg2/Probes/get_ram.sh`

case "$MEM" in
    50GB)
        echo "1600"
	;;
    25GB)
        echo "800"
	;;
    15GB)
	echo "480"
	;;
    8GB)
	echo "256"
	;;
    4GB)
	echo "128"
	;;
    2GB)
	echo "64"
	;;
    1GB)
	echo "32"
	;;
    500MB)
	echo "16"
	;;
esac
