#!/bin/bash
#If you wish to replace our default value for memcached memory in /etc/memcached.conf,
#edit the MEMCACHED_MEMORY variable in /root/MERCURY_CONFIG

. /root/MERCURY_CONFIG

RAM=`grep MemTotal /proc/meminfo | sed 's/[^0-9]*//g'`

if [[ -n "$MEMCACHED_MEMORY" ]]; then
   echo "$MEMCACHED_MEMORY"
elif (($RAM>=8000000)); then
    echo "512"
elif (($RAM>=4000000)); then
    echo "512"
elif (($RAM>=2000000)); then
    echo "256"
elif (($RAM>=1000000)); then
    echo "128"
else
    echo "64"
fi


