#!/bin/bash
#return the low value for memcached

RAM=`grep MemTotal /proc/meminfo | sed 's/[^0-9]*//g'`

if [[ -a /etc/memcached_memory ]]; then
    /etc/memcached_memory
elif (($RAM>=8000000)); then
    echo "512"
elif (($RAM>=4000000)); then
    echo "512"
elif (($RAM>=2000000)); then
    echo "256"
elif (($RAM>=1000000)); then
    echo "128"
else
    echo "64"
fi


