#!/bin/bash
#If you wish to replace our default value for apache maxclients in /etc/mysql/my.cnf,
#edit the MYSQL_MAX_CONNECTIONS variable in /etc/mercury/server_tuneables

if [[ -a /etc/mercury/server_tuneables ]]; then
. /etc/mercury/server_tuneables
fi

RAM=`grep MemTotal /proc/meminfo | sed 's/[^0-9]*//g'`

if [[ -n "$MYSQL_MAX_CONNECTIONS" ]]; then
   echo "$MYSQL_MAX_CONNECTIONS"
elif (($RAM>=8000000)); then
    echo "160"
elif (($RAM>=4000000)); then
    echo "80"
elif (($RAM>=2000000)); then
    echo "40"
elif (($RAM>=1000000)); then
    echo "20"
else
    echo "10"
fi
