#!/bin/bash
#set php memory usage

RAM=`grep MemTotal /proc/meminfo | sed 's/[^0-9]*//g'`

if [[ -a /etc/php5/apache2/memory.sh ]]; then
   /etc/php5/apache2/memory.sh
elif (($RAM>=2000000)); then
    echo "512"
elif (($RAM>=1000000)); then
    echo "256"
else
    echo "128"
fi

