#!/bin/bash
#If you wish to replace our default value for php memory in /etc/php5/apache2/php.ini,
#edit the PHP_MEMORY variable in /root/MERCURY_TUNEABLES

if [[ -a /root/MERCURY_TUNEABLES ]]; then
. /root/MERCURY_TUNEABLES
fi

RAM=`grep MemTotal /proc/meminfo | sed 's/[^0-9]*//g'`

if [[ -n "$PHP_MEMORY" ]]; then
   echo "$PHP_MEMORY"
elif (($RAM>=2000000)); then
    echo "512"
elif (($RAM>=1000000)); then
    echo "256"
else
    echo "128"
fi

