#!/bin/sh
#set apc memory usage

if (($RAM>=50000000)); then
    echo "4000"
elif (($RAM>=25000000)); then
    echo "200"
elif (($RAM>=15000000)); then
    echo "120"
elif (($RAM>=8000000)); then
    echo "64"
elif (($RAM>=4000000)); then
    echo "32"
elif (($RAM>=2000000)); then
    echo "16"
elif (($RAM>=1000000)); then
    echo "8"
else
    echo "4"
fi


