#!/bin/bash
#set tomcat6 memory usage

RAM=`grep MemTotal /proc/meminfo | sed 's/[^0-9]*//g'`

if [[ -a /etc/default/tomcat6_memory.sh ]]; then
   /etc/default/tomcat6_memory.sh
elif (($RAM>=50000000)); then
    echo "8192"
elif (($RAM>=25000000)); then
    echo "4096"
elif (($RAM>=15000000)); then
    echo "2048"
elif (($RAM>=8000000)); then
    echo "1024"
elif (($RAM>=4000000)); then
    echo "512"
elif (($RAM>=2000000)); then
    echo "256"
elif (($RAM>=1000000)); then
    echo "128"
else
    echo "64"
fi

