#!/bin/sh
#set tomcat max threads

RAM=$(grep MemTotal /proc/meminfo | sed 's/[^0-9]*//g')

if (($RAM>=50000000)); then
    echo "5000"
elif (($RAM>=25000000)); then
    echo "2500"
elif (($RAM>=15000000)); then
    echo "1500"
elif (($RAM>=8000000)); then
    echo "800"
elif (($RAM>=4000000)); then
    echo "400"
elif (($RAM>=2000000)); then
    echo "200"
elif (($RAM>=1000000)); then
    echo "100"
else
    echo "50"
fi
