#!/bin/sh
#set apc memory usage

if (($RAM>=50000000)); then
    echo "1600"
elif (($RAM>=25000000)); then
    echo "800"
elif (($RAM>=15000000)); then
    echo "480"
elif (($RAM>=8000000)); then
    echo "256"
elif (($RAM>=4000000)); then
    echo "128"
elif (($RAM>=2000000)); then
    echo "64"
elif (($RAM>=1000000)); then
    echo "32"
else
    echo "16"
fi

