#!/bin/bash
#any output from this script will be added to the vcl_recv subroutine in /etc/varnish/default.vcl
#add any additions to /etc/varnish/vcl_recv.sh
#we source a file outside of /var/lib/bcfg2 so that it's not overwritten by /usr/local/bin/update_mercury.sh 
#or an bzr merge within /var/lib/bcfg2

if [[ -a /etc/varnish/vcl_recv.sh ]]; then
   /etc/varnish/vcl_recv.sh
fi