#!/bin/bash
#set tomcat max threads

RAM=`grep MemTotal /proc/meminfo | sed 's/[^0-9]*//g'`

if [[ -a /etc/tomcat6/max_threads.sh ]]; then
   /etc/tomcat6/max_threads.sh
elif (($RAM>=2000000)); then
    echo "200"
elif (($RAM>=1000000)); then
    echo "100"
else
    echo "50"
fi
