#!/bin/bash
#If you wish to replace our default value for tomcat memory in /etc/default/tomcat6,
#edit the TOMCAT_MEMORY variable in /root/MERCURY_CONFIG

. /root/MERCURY_CONFIG

RAM=`grep MemTotal /proc/meminfo | sed 's/[^0-9]*//g'`

if [[ -n "$TOMCAT_MEMORY" ]]; then
   echo "$TOMCAT_MEMORY"
elif (($RAM>=8000000)); then
    echo "1024"
elif (($RAM>=4000000)); then
    echo "512"
elif (($RAM>=2000000)); then
    echo "256"
elif (($RAM>=1000000)); then
    echo "128"
else
    echo "64"
fi

