#!/bin/sh
#set tomcat max threads

MEM=`/var/lib/bcfg2/Probes/get_ram.sh`

case "$MEM" in
    50GB)
        echo "5000"
        ;;
    25GB)
        echo "2500"
        ;;
    15GB)
        echo "1500"
        ;;
    8GB)
        echo "800"
        ;;
    4GB)
        echo "400"
        ;;
    2GB)
        echo "200"
        ;;
    1GB)
        echo "100"
        ;;
    500MB)
        echo "50"
        ;;
esac
