#!/bin/bash
#If you wish to replace our default value for vcl_fetch in /etc/varnish/default.vlc,
#edit the VARNISH_VCL_FETCH variable in /root/TUNEABLE_CONFIGS.sh

. /root/TUNEABLE_CONFIGS.sh

if [[ -n "$VARNISH_VCL_FETCH" ]]; then
   echo "$VARNISH_VCL_FETCH"
fi

