#!/bin/sh
#set varnish memory usage

MEM=`/var/lib/bcfg2/Probes/get_ram.sh`

case "$MEM" in
    50GB)
        echo "12800M"
	;;
    25GB)
        echo "6400M"
	;;
    15GB)
	echo "3840M"
	;;
    8GB)
	echo "2048M"
	;;
    4GB)
	echo "1024M"
	;;
    2GB)
	echo "512M"
	;;
    1GB)
	echo "256M"
	;;
    500MB)
	echo "128M"
	;;
esac
