#!/bin/bash
#If you wish to replace our default value for vcl_fetch in /etc/varnish/default.vlc,
#edit the VARNISH_VCL_FETCH variable in /etc/mercury/tuneable_configs

if [[ -a /etc/mercury/tuneable_configs ]]; then
. /etc/mercury/tuneable_configs
fi

if [[ -n "$VARNISH_VCL_FETCH" ]]; then
   echo "$VARNISH_VCL_FETCH"
fi

