#!/bin/bash
#If you wish to replace our default value for vcl_error in /etc/varnish/default.vlc,
#edit the VARNISH_VCL_ERROR variable in /root/MERCURY_TUNEABLES

if [[ -a /root/MERCURY_TUNEABLES ]]; then
. /root/MERCURY_TUNEABLES
fi

if [[ -n "$VARNISH_VCL_ERROR" ]]; then
   echo "$VARNISH_VCL_ERROR"
fi
