#!/bin/bash
#If you wish to replace our default value for vcl_recv in /etc/varnish/default.vlc,
#edit the VARNISH_VCL_RECV variable in /root/MERCURY_CONFIG

. /root/MERCURY_CONFIG

if [[ -n "$VARNISH_VCL_RECV" ]]; then
   echo "$VARNISH_VCL_RECV"
fi