#!/bin/bash
#If you wish to replace our default value for apache maxclients in /etc/apache2/apache.conf,
#edit the APACHE_MAXCLIENTS variable in /etc/pantheon/server_tuneables

if [[ -a /etc/pantheon/server_tuneables ]]; then
. /etc/pantheon/server_tuneables
fi

RAM=`grep MemTotal /proc/meminfo | sed 's/[^0-9]*//g'`

if [[ -n "$APACHE_MAXCLIENTS" ]]; then
   echo "$APACHE_MAXCLIENTS"
elif (($RAM>=8000000)); then
    echo "80"
elif (($RAM>=4000000)); then
    echo "40"
elif (($RAM>=2000000)); then
    echo "20"
elif (($RAM>=1000000)); then
    echo "10"
else
    echo "5"
fi
