#!/bin/bash
#If you wish to replace our default value for mysql paths in /etc/apparmor.d/usr.sbin.mysqld,
#edit the APPARMOR_MYSQLD variable in /etc/mercury/server_tuneables

if [[ -a /etc/mercury/server_tuneables ]]; then
. /etc/mercury/server_tuneables
fi

if [[ -n "$APPARMOR_MYSQLD" ]]; then
    echo "$APPARMOR_MYSQLD"
else
    echo "/mnt/mysql/** rwkl,"
fi


