#!/bin/bash

OUTPUT=""

if [ -e /etc/debian_version ]; then
    # debian based
    OUTPUT=$OUTPUT'\n'`echo group:deb`
    if [ -e /etc/lsb-release ]; then
        # variant
        . /etc/lsb-release
        OUTPUT=$OUTPUT'\n'`echo group:$DISTRIB_CODENAME`
        DEBIAN_VERSION=$(echo "$DISTRIB_ID" | tr '[A-Z' '[a-z]')
        OUTPUT=$OUTPUT'\n'`echo group:$DEBIAN_VERSION`
    else
    # debian
        ARGS="-e"
        OS_GROUP=`cat /etc/debian_version`
        OUTPUT=$OUTPUT'\n'`echo group:debian`
        case "$OS_GROUP" in
            "5.0")
             OUTPUT=$OUTPUT'\n'`echo group:lenny`
             ;;
             "sid")
             OUTPUT=$OUTPUT'\n'`echo group:sid`
             ;;
        esac
    fi
elif [ -e /etc/redhat-release ]; then
    # redhat based
    ARGS="-e"
    OUTPUT=$OUTPUT'\n'`echo group:rpm`
    OS_GROUP=`cat /etc/redhat-release | cut -d' ' -f1 | tr '[A-Z]' '[a-z]'`
    REDHAT_VERSION=`cat /etc/redhat-release | cut -d' ' -f3`
    MAJOR_REDHAT_VERSION=${REDHAT_VERSION:0:1}
    case "$OS_GROUP" in
        "centos" | "fedora")
        OUTPUT=$OUTPUT'\n'`echo group:$OS_GROUP`
        OUTPUT=$OUTPUT'\n'`echo group:$OS_GROUP$MAJOR_REDHAT_VERSION`
        OUTPUT=$OUTPUT'\n'`echo group:$OS_GROUP$REDHAT_VERSION`
        ;;
    esac
else    
    exit 0
fi

# get the proper architecture
ARCH=`uname -m`
case "$ARCH" in
        "x86_64")
        if [ "$OS_GROUP" == 'centos' ]; then
                OUTPUT=$OUTPUT'\n'`echo group:$ARCH`
        else
                OUTPUT=$OUTPUT'\n'`echo group:amd64`
        fi
        ;;
        "i386" | "i686")
        OUTPUT=$OUTPUT'\n'`echo group:i386`
        ;;
        "sparc64")
        OUTPUT=$OUTPUT'\n'`echo group:sparc64`
        ;;
esac


# output the result of all the group probing
# (interpreting the backslashed newlines)
echo -e $OUTPUT

