#!/bin/bash
#If you wish to replace our default value for php memory in /etc/php5/apache2/php.ini,
#edit the PHP_UPLOAD_MAX_FILESIZE variable in /etc/pantheon/server_tuneables

if [[ -a /etc/pantheon/server_tuneables ]]; then
. /etc/pantheon/server_tuneables
fi

RAM=`grep MemTotal /proc/meminfo | sed 's/[^0-9]*//g'`

if [[ -n "$PHP_UPLOAD_MAX_FILESIZE" ]]; then
   echo "$PHP_UPLOAD_MAX_FILESIZE"
else
    echo "8"
fi

