#!/bin/bash
#If you wish to replace our default value for tomcat memory in /etc/default/tomcat6,
#edit the TOMCAT_MEMORY variable in /etc/mercury/server_tuneables

if [[ -a /etc/mercury/server_tuneables ]]; then
. /etc/mercury/server_tuneables
fi

RAM=`grep MemTotal /proc/meminfo | sed 's/[^0-9]*//g'`

if [[ -n "$TOMCAT_MEMORY" ]]; then
   echo "$TOMCAT_MEMORY"
else
    echo "96"
fi

