#!/bin/bash
#If you wish to replace our default value for varnish memory in /etc/default/varnish,
#edit the VARNISH_MEMORY variable in /etc/mercury/server_tuneables

if [[ -a /etc/mercury/server_tuneables ]]; then
. /etc/mercury/server_tuneables
fi

RAM=`grep MemTotal /proc/meminfo | sed 's/[^0-9]*//g'`

if [[ -n "$VARNISH_MEMORY" ]]; then
   echo "$VARNISH_MEMORY"
elif (($RAM>=8000000)); then
    echo "512"
elif (($RAM>=4000000)); then
    echo "256"
elif (($RAM>=2000000)); then
    echo "128"
elif (($RAM>=1000000)); then
    echo "64"
else
    echo "32"
fi
