#!/bin/bash
#If you wish to replace our default value for vcl_fetch in /etc/varnish/default.vlc,
#edit the VARNISH_VCL_FETCH variable in /etc/pantheon/server_tuneables

if [[ -a /etc/pantheon/server_tuneables ]]; then
. /etc/pantheon/server_tuneables
fi

if [[ -n "$VARNISH_VCL_FETCH" ]]; then
   echo "$VARNISH_VCL_FETCH"
fi

