#!/bin/bash
#If you wish to replace our default value for vcl_hash in /etc/varnish/default.vlc,
#edit the VARNISH_VCL_RECV variable in /etc/mercury/server_tuneables

if [[ -a /etc/mercury/server_tuneables ]]; then
. /etc/mercury/server_tuneables
fi

if [[ -n "$VARNISH_VCL_HASH" ]]; then
   echo "$VARNISH_VCL_HASH"
fi
