#!/bin/bash
#If you wish to replace our default value for vcl_error in /etc/varnish/default.vlc,
#edit the VARNISH_VCL_ERROR variable in /etc/pantheon/server_tuneables

if [[ -a /etc/pantheon/server_tuneables ]]; then
. /etc/pantheon/server_tuneables
fi

if [[ -n "$VARNISH_VCL_ERROR" ]]; then
   echo "$VARNISH_VCL_ERROR"
fi
